# Generated by Django 5.2.4 on 2025-07-16 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=400)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='bookstore.author')),
                ('category', models.ManyToManyField(related_name='books', to='bookstore.category')),
            ],
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('ISBN_number', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ISBN', to='bookstore.book')),
            ],
        ),
    ]
