# Generated by Django 5.2.4 on 2025-07-16 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
